# Generated by Django 4.0.5 on 2023-08-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre autor')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellido')),
                ('nacionalidad', models.CharField(max_length=20, verbose_name='Nacionalidad')),
                ('edad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre lector')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellido')),
                ('nacionalidad', models.CharField(max_length=20, verbose_name='Nacionalidad')),
                ('edad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo')),
                ('fechaLanzamiento', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('portada', models.ImageField(upload_to='imagenes/')),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('autores', models.ManyToManyField(to='app1.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPrestamo', models.DateField(verbose_name='Fecha del prestamo')),
                ('fechaDevolucion', models.DateField(verbose_name='Fecha de devolucion')),
                ('devuelto', models.BooleanField(verbose_name='Devuelto: ')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.libro')),
            ],
        ),
    ]
